migrate everthing to github action

diff --git a/.github/workflows/test_kube.yaml b/.github/workflows/test_kube.yaml
--- a/.github/workflows/test_kube.yaml
+++ b/.github/workflows/test_kube.yaml
@@ -4,6 +4,7 @@ jobs:
     name: Test commit
     runs-on: ubuntu-24.04
     steps:
+      # setup
       - name: Install deps
         run: |-
           set -euo pipefail
@@ -25,6 +26,7 @@ jobs:
           sed -i \
               -e "s|/run/user/1000/|${XDG_RUNTIME_DIR:-/run/user/1000}/|" \
               kube/*.yaml
+      # startup
       - name: Create pods
         run: |-
           set -euo pipefail
@@ -43,15 +45,57 @@ jobs:
       - name: Wait for healthy state
         run: |-
           set -euo pipefail
-          yq -N '. as $parent | (
+          yq -ot '. as $parent | (
             .spec.containers[] | select(.livenessProbe) | $parent.metadata.name + "-" + .name,
             .spec.template.spec.containers[] | select(.livenessProbe) | $parent.metadata.name + "-pod-" + .name
           )' kube/*.yaml |
           xargs -t podman wait --condition healthy
         timeout-minutes: 2
-      - name: Pods
+      # testing
+      - name: Test Dozzle
+        run: |-
+          set -euo pipefail
+          USR=$(podman secret inspect secrets --showsecret --format "{{.SecretData}}" | yq -ot .data.dozzle_user)
+          DOMAIN=$(podman secret inspect secrets --showsecret --format "{{.SecretData}}" | yq -ot .data.nextcloud_domain)
+          curl -ikLsS --location-trusted --user "$USR:$USR" \
+            --connect-to "$DOMAIN:80:127.0.0.1:8080" \
+            --connect-to "$DOMAIN:443:127.0.0.1:8443" \
+            "http://$DOMAIN/dozzle/" |
+            grep -q "^HTTP/[1-9\.]* 200"
+      - name: Test Nextcloud
+        run: |-
+          set -euo pipefail
+          DOMAIN=$(podman secret inspect caddy --showsecret --format "{{.SecretData}}" | yq -ot .data.nextcloud_domain)
+          curl -ikLsS \
+            --connect-to "$DOMAIN:80:127.0.0.1:8080" \
+            --connect-to "$DOMAIN:443:127.0.0.1:8443" \
+            "http://$DOMAIN/status.php" |
+            grep -q '"installed":true'
+      - name: Test Redirection
+        run: |-
+          set -euo pipefail
+          DOMAIN=$(podman secret inspect caddy --showsecret --format "{{.SecretData}}" | yq -ot .data.redir_domain)
+          TARGET=$(podman secret inspect caddy --showsecret --format "{{.SecretData}}" | yq -ot .data.redir_target)
+          {
+            curl -ikLsS --max-redirs 1 \
+            --connect-to "$DOMAIN:80:127.0.0.1:8080" \
+            --connect-to "$DOMAIN:443:127.0.0.1:8443" \
+            "http://$DOMAIN/test.php" || [ $? = 47 ]
+          } |
+            grep -q "Location: $TARGET"
+      - name: Test Wordpress
+        run: |-
+          set -euo pipefail
+          DOMAIN=$(podman secret inspect caddy --showsecret --format "{{.SecretData}}" | yq -ot .data.wordpress1_domain)
+          curl -ikLsS \
+            --connect-to "$DOMAIN:80:127.0.0.1:8080" \
+            --connect-to "$DOMAIN:443:127.0.0.1:8443" \
+            "http://$DOMAIN/wp-admin/install.php" |
+            grep -q "^HTTP/[1-9\.]* 200"
+      # state if failed
+      - name: State pods
         run: podman pod ls
-        if: ${{ always() }}
-      - name: Containers
+        if: ${{ failure() }}
+      - name: State containers
         run: podman ps -a
-        if: ${{ always() }}
+        if: ${{ failure() }}
